# Configuration of Economobs. For help, visit https://docs.axelli.net/

# What stacker should the plugin look for?
# Current list: NONE, WILDSTACKER
stacker: NONE

# Multipliers.
# If any conditions are true, they will be considered towards the output amount.
# Make sure to balance this properly if you use both. You can leave any category empty if you wish not to use it.
multipliers:
  weapons:
    - DIAMOND_SWORD 1.2
  worlds:
    - world1 1.8

# A list of worlds where money wont be given.
world-blacklist:
  - world2