# Configuration of Economobs. For help, visit https://docs.axelli.net/

# What stacker should the plugin look for?
# Current list: NONE, WILDSTACKER, STACKMOB
stacker: NONE

# Message handling.
message:
  # Should the plugin send messages about money gained?
  enabled: true

  # How should the plugin display messages when a player is given money?
  # NOTE: Some options will only work with select versions. You can see which below.
  # OPTIONS: CHAT, ACTION_BAR (1.12+), HOLOGRAM (1.12+)
  message-type: CHAT

  # HOLOGRAMS
  # This will only work if you have holograms set as your type.
  holograms:
    # OPTIONS: STAY, FLOAT, BOUNCE
    animation: STAY
    # This option will effect animations.
    # How long should the hologram stay? This is in seconds.
    duration: 1

# Multipliers.
# If any conditions are true, they will be considered towards the output amount.
# Make sure to balance this properly if you use both. You can leave any category empty if you wish not to use it.
multipliers:
  weapons:
    - DIAMOND_SWORD 1.2
  worlds:
    - world1 1.8

# A list of worlds where money wont be given.
world-blacklist:
  - world2