# Configuration of Economobs. For help, visit https://docs.axelli.net/

# What stacker should the plugin look for?
# Current list: NONE, WILDSTACKER, STACKMOB
stacker: NONE

# Message handling.
message:
  # Should the plugin send messages about money gained?
  enabled: true

  # How should the plugin display messages when a player is given money?
  # NOTE: Some options will only work with select versions. You can see which below.
  # OPTIONS: CHAT, ACTION_BAR (1.12+), HOLOGRAM (1.12+)
  message-type: CHAT

  # HOLOGRAMS
  # This will only work if you have holograms set as your type.
  holograms:
    # OPTIONS: STAY, FLOAT, BOUNCE
    animation: STAY
    # This option will affect animations.
    # How long should the hologram stay? This is in seconds.
    duration: 1

# Multiplier handling.
# Down below are configurable multiplier groups.
# If any conditions are true, they will be considered towards the output amount.
# Make sure to balance this properly if you use multipliers. You can leave any category empty with [] if you wish not to use it.
multipliers:
  example:
    # Specific mob multipliers.
    mobs:
      - CHICKEN 1.1
      - PIG 1.1
      - COW 1.1
    # The tool used to kill the mob.
    weapons:
      - DIAMOND_SWORD 1.2
    # The world the mob died in.
    worlds:
      - real_world 1.1
  # More examples...
  coal:
    mobs:
      - COW 1.5
    weapons:
      - DIAMOND_SWORD 1.5
  diamond:
    mobs:
      - COW 2
    weapons:
      - DIAMOND_SWORD 2.5

# A list of worlds where money won't be given.
world-blacklist:
  - world2